name: MSC_Premium_Watcher

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Process Keys
        run: |
          # 1. Загрузка
          RAW=$(curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS.txt)
          
          # 2. Очистка и Красивые названия (VK, YT, Instagram и т.д.)
          COOKED=$(echo "$RAW" | grep "vless://" | \
            sed 's/#.*VK.*/#🔵 VK | MSC Premium/' | \
            sed 's/#.*YouTube.*/#🔴 YouTube | MSC Premium/' | \
            sed 's/#.*TikTok.*/#⚫ TikTok | MSC Premium/' | \
            sed 's/#.*INSTA.*/#🟣 Instagram | MSC Premium/' | \
            sed 's/#.*WEB.*/#🌐 Web | MSC Premium/' | \
            sed 's/#.*GPT.*/#🤖 ChatGPT | MSC Premium/' | \
            sed 's/#.*GAME.*/#🎮 Gaming | MSC Premium/' | \
            sed 's/#.*GP.*/#🤖 ChatGPT | MSC Premium/' | \
            sed '/#/! s/$/#⭐ MSC Premium VPN/' | \
            tr -d '\r')
          
          # 3. Создание JSON
          echo "$COOKED" > keys.txt
          JSON=$(jq -Rs '{"files": {"MSC-Premium-VPN": {"content": .}}}' keys.txt)
          
          # 4. Обновление Gist
          curl -L -s -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GIST_SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/${{ secrets.GIST_ID }} \
            -d "$JSON"
            
          # 5. Telegram
          URL="https://gist.githubusercontent.com/C0RBIH/${{ secrets.GIST_ID }}/raw/MSC-Premium-VPN"
          MSG="✅ Подписка *MSC Premium VPN* обновлена!%0A%0AСерверы переименованы (ВК, YT, и др.)%0A%0A🔗 Ссылка:%0A$URL"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            -d "text=$MSG"
